name: Build Docker to AWS ECR

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string        
      aws_repo:
        required: true
        type: string
      image_tag_prefix:
        required: false
        type: string
      args:
        description: "List of build-time variables"
        required: false
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
    outputs:
      aws_repo_image:
        value: ${{ jobs.docker_build_to_aws_ecr.outputs.aws_repo_image }}

jobs:
  docker_build_to_aws_ecr:
    runs-on: ubuntu-20.04
    outputs:
      aws_repo_image: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.aws_repo }}:${{ inputs.image_tag_prefix }}${{ github.sha }}
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}
          mask-aws-account-id: no
      - 
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - 
        name: Build image and push to AWS ECR
        uses: docker/build-push-action@v2
        with:
          build-args: ${{ inputs.args }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.aws_repo }}:${{ inputs.image_tag_prefix }}${{ github.sha }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
